version: "1"
name: nifi-compose

services:
 nifi:
  container_name: nifi
  image: apache/nifi:latest
  restart: unless-stopped
  volumes:
   - /nifi:/nifi
  ports:
   - "8080:8080"
  environment:
   - NIFI_WEB_HTTP_PORT=8080
   - SINGLE_USER_CREDENTIALS_USERNAME=admin
   - SINGLE_USER_CREDENTIALS_PASSWORD=senha123456789
